# Generated by Django 4.1 on 2023-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarSystem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.IntegerField(default=3),
        ),
    ]
